<a href="https://colab.research.google.com/github/curttay1-dev/My-python-pandas-projects/blob/main/Pandas_Day_1_June_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# install library if needed
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# import pandas library
import pandas as pd
# alias pandas library as pd

In [ ]:
pd.__version__

'2.2.2'

# Creating a dataframe

In [ ]:
# list object
mylist = ["apple", "banana", "cherry"]

In [ ]:
# dataframe from a list
pd.DataFrame(mylist)

        0
0   apple
1  banana
2  cherry

In [ ]:
mydict = {"name":"Yusuf",
          "age":18,
          "location":"UK"}

In [ ]:
pd.DataFrame(mydict, index=[0])

    name  age location
0  Yusuf   18       UK

# Import dataset

In [ ]:
df = pd.read_excel("/content/student.xlsx")
# import and assign to df
# df is short for dataframe

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
df = pd.read_csv("/content/student.csv")

# EDA (Exploratory Data Analaysis)

In [ ]:
df

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
# top 5 rows
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
# top 10 rows
df.head(10)

   id         name  class  mark  gender
0   1     John Deo   Four    75  female
1   2     Max Ruin  Three    85    male
2   3       Arnold  Three    55    male
3   4   Krish Star   Four    60  female
4   5    John Mike   Four    60  female
5   6    Alex John   Four    55    male
6   7  My John Rob  Fifth    78    male
7   8       Asruid   Five    85    male
8   9      Tes Qry    Six    78     NaN
9  10     Big John   Four    55  female

In [ ]:
# last 5 rows
df.tail()

    id         name  class  mark  gender
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.tail(3)

    id        name  class  mark  gender
32  33   Kenn Rein    Six    96  female
33  34    Gain Toe  Seven    69    male
34  35  Rows Noump    Six    88  female

In [ ]:
# random sample data
df.sample()

    id name  class  mark  gender
12  13  Kty  Seven    88  female

In [ ]:
# random sample data
df.sample(3)

    id        name class  mark  gender
3    4  Krish Star  Four    60  female
20  21  Babby John  Four    69  female
8    9     Tes Qry   Six    78     NaN

In [ ]:
# number of rows and columns
df.shape
#its an attribute. no ()

(35, 5)

In [ ]:
# dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

- compare non-null count vs number of entries.
* name has 34 non-null
* class has 34 non-null
* gender has 33 non-null
**These columns have missing values.**

In [ ]:
# name of the columns
df.columns

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [ ]:
# statistical summary
df.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

- compare mean vs std. std must be much less than mean. if its close or higher, there are outliers.
- 50% median. 50 % of the marks of the students are equal to higher than 79.
- 25%. 25% of all student have mark less than 62.5

In [ ]:
# number of rows
len(df)

35

In [ ]:
# rows * columns
df.size
# 35 * 5 = 175

175

In [ ]:
# datatypes of the columns
df.dtypes

id         int64
name      object
class     object
mark       int64
gender    object
dtype: object

- object - string data type
- int64 - integer
- float64 - float

In [ ]:
# Counts missing values per column.
df.isnull().sum()

id        0
name      1
class     1
mark      0
gender    2
dtype: int64

In [ ]:
# Counts duplicate rows.
df.duplicated().sum()

np.int64(0)

# Slicing Dataframe

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
# use [] after df to select column or columns
df["name"]

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26            NaN
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [ ]:
df["class"]

0      Four
1     Three
2     Three
3      Four
4      Four
5      Four
6     Fifth
7      Five
8       Six
9      Four
10      Six
11      Six
12    Seven
13    Seven
14      NaN
15     Four
16      Six
17     Five
18     Nine
19     Nine
20     Four
21    Seven
22    Eight
23    Seven
24    Seven
25    Seven
26    Three
27    Seven
28    Seven
29      Six
30     Four
31    Seven
32      Six
33    Seven
34      Six
Name: class, dtype: object

In [ ]:
# use df.column_name
df.id

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
32    33
33    34
34    35
Name: id, dtype: int64

In [ ]:
df.class

SyntaxError: invalid syntax (1584895042.py, line 1)

In [ ]:
df["class"].head()

0     Four
1    Three
2    Three
3     Four
4     Four
Name: class, dtype: object

In [ ]:
# average mark
df["mark"].mean()

np.float64(74.65714285714286)

In [ ]:
# median mark
df["mark"].median()

79.0

- you need to place name of the column in a list
- ["name", "class"] list of the columns

In [ ]:
# you need to double [] if you want to return more than 1 column
df[["name", "class"]].head()

         name  class
0    John Deo   Four
1    Max Ruin  Three
2      Arnold  Three
3  Krish Star   Four
4   John Mike   Four

In [ ]:
df[["name", "class", "mark"]].sample()

     name class  mark
16  Tumyu   Six    54

# loc and iloc operators

In [ ]:
df.loc[1]

id               2
name      Max Ruin
class        Three
mark            85
gender        male
Name: 1, dtype: object

In [ ]:
df.iloc[1]

id               2
name      Max Ruin
class        Three
mark            85
gender        male
Name: 1, dtype: object

- df.loc[rows, column name]
- df.iloc[rows, colum index]

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
# return name of the 1st student
df.loc[0, "name"]

'John Deo'

In [ ]:
# mark at student index 2
df.loc[2, "mark"]

np.int64(55)

- first row is index 0
- second row is index 1
- fist column is at index 0

In [ ]:
# return name of the 1st student
# df.loc[0, "name"]
# return name of the 1st student. name column is at index 1
df.iloc[0, 1]

'John Deo'

In [ ]:
# mark at student index 2
#df.loc[2, "mark"]
df.iloc[2, 3]

np.int64(55)

In [ ]:
# name, class of first 5 using loc
df.loc[0:4, ["name", "class"] ]

         name  class
0    John Deo   Four
1    Max Ruin  Three
2      Arnold  Three
3  Krish Star   Four
4   John Mike   Four

In [ ]:
# name, class of first 5 using iloc
df.iloc[0:5, [1,2]]
# iloc doesnt include the stopping point in the result

         name  class
0    John Deo   Four
1    Max Ruin  Three
2      Arnold  Three
3  Krish Star   Four
4   John Mike   Four

In [ ]:
df.loc[[0,5], ["name", "mark"]]

        name  mark
0   John Deo    75
5  Alex John    55

In [ ]:
df.iloc[[0,5], [1,3]]

        name  mark
0   John Deo    75
5  Alex John    55

In [ ]:
df.loc[10:15, ["name", "gender", "mark"]]

        name  gender  mark
10    Ronald  female    89
11     Recky  female    94
12       Kty  female    88
13      Bigy  female    88
14  Tade Row    male    88
15     Gimmy    male    88

In [ ]:
df.iloc[10:15, 1:3]

        name  class
10    Ronald    Six
11     Recky    Six
12       Kty  Seven
13      Bigy  Seven
14  Tade Row    NaN

# Filtering Dataframe

In [ ]:
df.loc[df["mark"]>90, ["name", "class", "mark"]]

         name class  mark
11      Recky   Six    94
32  Kenn Rein   Six    96

In [ ]:
# df.iloc[df["mark"]>90, [1,2,3]]

In [ ]:
df.loc[df["class"]=="Six", :]
# : means return all range

    id        name class  mark  gender
8    9     Tes Qry   Six    78     NaN
10  11      Ronald   Six    89  female
11  12       Recky   Six    94  female
16  17       Tumyu   Six    54    male
29  30   Reppy Red   Six    79  female
32  33   Kenn Rein   Six    96  female
34  35  Rows Noump   Six    88  female

In [ ]:
df.loc[df["gender"]=="female", ["name", "gender"]]

          name  gender
0     John Deo  female
3   Krish Star  female
4    John Mike  female
9     Big John  female
10      Ronald  female
11       Recky  female
12         Kty  female
13        Bigy  female
19      Jackly  female
20  Babby John  female
21      Reggid  female
27   Rojj Base  female
29   Reppy Red  female
31   Binn Rott  female
32   Kenn Rein  female
34  Rows Noump  female

- filter by multiple condition

In [ ]:
df.loc[(df["class"]=="Five") & (df["gender"]=="male"), ["name", "class", "gender"]]

      name class gender
7   Asruid  Five   male
17   Honny  Five   male

In [ ]:
df.loc[(df["class"]=="Seven") & (df["mark"]>=70), ["name", "class", "mark"]]

         name  class  mark
12        Kty  Seven    88
13       Bigy  Seven    88
23  Tiddy Now  Seven    78
24   Giff Tow  Seven    88
25     Crelea  Seven    79
27  Rojj Base  Seven    86
31  Binn Rott  Seven    90

In [ ]:
# write condition insidei [] to filter dataframe using slicing method
df[df["mark"]>85]

    id         name  class  mark  gender
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
24  25     Giff Tow  Seven    88    male
27  28    Rojj Base  Seven    86  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
34  35   Rows Noump    Six    88  female

In [ ]:
df[df["class"]=="Four"]

    id         name class  mark  gender
0    1     John Deo  Four    75  female
3    4   Krish Star  Four    60  female
4    5    John Mike  Four    60  female
5    6    Alex John  Four    55    male
9   10     Big John  Four    55  female
15  16        Gimmy  Four    88    male
20  21   Babby John  Four    69  female
30  31  Marry Toeey  Four    88    male

In [ ]:
df[(df["class"]=="Four") & (df["gender"]=="female")]

    id        name class  mark  gender
0    1    John Deo  Four    75  female
3    4  Krish Star  Four    60  female
4    5   John Mike  Four    60  female
9   10    Big John  Four    55  female
20  21  Babby John  Four    69  female

In [ ]:
df[(df["class"]=="Four") |(df["gender"]=="female")]
# filter by class four or gender female

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
15  16        Gimmy   Four    88    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
27  28    Rojj Base  Seven    86  female
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
34  35   Rows Noump    Six    88  female

In [ ]:
df.filter(items=['name', 'mark'])

           name  mark
0      John Deo    75
1      Max Ruin    85
2        Arnold    55
3    Krish Star    60
4     John Mike    60
5     Alex John    55
6   My John Rob    78
7        Asruid    85
8       Tes Qry    78
9      Big John    55
10       Ronald    89
11        Recky    94
12          Kty    88
13         Bigy    88
14     Tade Row    88
15        Gimmy    88
16        Tumyu    54
17        Honny    75
18        Tinny    18
19       Jackly    65
20   Babby John    69
21       Reggid    55
22        Herod    79
23    Tiddy Now    78
24     Giff Tow    88
25       Crelea    79
26          NaN    81
27    Rojj Base    86
28  Tess Played    55
29    Reppy Red    79
30  Marry Toeey    88
31    Binn Rott    90
32    Kenn Rein    96
33     Gain Toe    69
34   Rows Noump    88

In [ ]:
df.filter(like='me')

           name
0      John Deo
1      Max Ruin
2        Arnold
3    Krish Star
4     John Mike
5     Alex John
6   My John Rob
7        Asruid
8       Tes Qry
9      Big John
10       Ronald
11        Recky
12          Kty
13         Bigy
14     Tade Row
15        Gimmy
16        Tumyu
17        Honny
18        Tinny
19       Jackly
20   Babby John
21       Reggid
22        Herod
23    Tiddy Now
24     Giff Tow
25       Crelea
26          NaN
27    Rojj Base
28  Tess Played
29    Reppy Red
30  Marry Toeey
31    Binn Rott
32    Kenn Rein
33     Gain Toe
34   Rows Noump

In [ ]:
df.query("mark > 60")

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.query('gender == "female"')

    id        name  class  mark  gender
0    1    John Deo   Four    75  female
3    4  Krish Star   Four    60  female
4    5   John Mike   Four    60  female
9   10    Big John   Four    55  female
10  11      Ronald    Six    89  female
11  12       Recky    Six    94  female
12  13         Kty  Seven    88  female
13  14        Bigy  Seven    88  female
19  20      Jackly   Nine    65  female
20  21  Babby John   Four    69  female
21  22      Reggid  Seven    55  female
27  28   Rojj Base  Seven    86  female
29  30   Reppy Red    Six    79  female
31  32   Binn Rott  Seven    90  female
32  33   Kenn Rein    Six    96  female
34  35  Rows Noump    Six    88  female

# Sort Values

In [ ]:
df.sort_values(by="mark")

    id         name  class  mark  gender
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
2    3       Arnold  Three    55    male
5    6    Alex John   Four    55    male
28  29  Tess Played  Seven    55    male
21  22       Reggid  Seven    55  female
9   10     Big John   Four    55  female
4    5    John Mike   Four    60  female
3    4   Krish Star   Four    60  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
0    1     John Deo   Four    75  female
17  18        Honny   Five    75    male
8    9      Tes Qry    Six    78     NaN
23  24    Tiddy Now  Seven    78    male
6    7  My John Rob  Fifth    78    male
22  23        Herod  Eight    79    male
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
1    2     Max Ruin  Three    85    male
7    8       Asruid   Five    85    male
27  28    Rojj Base  Seven    86  female
12  13          Kty  Seven    88  female
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
14  15     Tade Row    NaN    88    male
30  31  Marry Toeey   Four    88    male
13  14         Bigy  Seven    88  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

In [ ]:
df.sort_values(by="name")

    id         name  class  mark  gender
5    6    Alex John   Four    55    male
2    3       Arnold  Three    55    male
7    8       Asruid   Five    85    male
20  21   Babby John   Four    69  female
9   10     Big John   Four    55  female
13  14         Bigy  Seven    88  female
31  32    Binn Rott  Seven    90  female
25  26       Crelea  Seven    79    male
33  34     Gain Toe  Seven    69    male
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
22  23        Herod  Eight    79    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
0    1     John Deo   Four    75  female
4    5    John Mike   Four    60  female
32  33    Kenn Rein    Six    96  female
3    4   Krish Star   Four    60  female
12  13          Kty  Seven    88  female
30  31  Marry Toeey   Four    88    male
1    2     Max Ruin  Three    85    male
6    7  My John Rob  Fifth    78    male
11  12        Recky    Six    94  female
21  22       Reggid  Seven    55  female
29  30    Reppy Red    Six    79  female
27  28    Rojj Base  Seven    86  female
10  11       Ronald    Six    89  female
34  35   Rows Noump    Six    88  female
14  15     Tade Row    NaN    88    male
8    9      Tes Qry    Six    78     NaN
28  29  Tess Played  Seven    55    male
23  24    Tiddy Now  Seven    78    male
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
26  27          NaN  Three    81     NaN

In [ ]:
df.sort_values(by="mark", ascending=False)

    id         name  class  mark  gender
32  33    Kenn Rein    Six    96  female
11  12        Recky    Six    94  female
31  32    Binn Rott  Seven    90  female
10  11       Ronald    Six    89  female
30  31  Marry Toeey   Four    88    male
34  35   Rows Noump    Six    88  female
24  25     Giff Tow  Seven    88    male
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
27  28    Rojj Base  Seven    86  female
7    8       Asruid   Five    85    male
1    2     Max Ruin  Three    85    male
26  27          NaN  Three    81     NaN
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
22  23        Herod  Eight    79    male
6    7  My John Rob  Fifth    78    male
23  24    Tiddy Now  Seven    78    male
8    9      Tes Qry    Six    78     NaN
17  18        Honny   Five    75    male
0    1     John Deo   Four    75  female
33  34     Gain Toe  Seven    69    male
20  21   Babby John   Four    69  female
19  20       Jackly   Nine    65  female
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
2    3       Arnold  Three    55    male
5    6    Alex John   Four    55    male
9   10     Big John   Four    55  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
16  17        Tumyu    Six    54    male
18  19        Tinny   Nine    18    male

In [ ]:
df.sort_values(by="mark", ascending=False).head().loc[df["gender"]=="female", :]

    id       name  class  mark  gender
32  33  Kenn Rein    Six    96  female
11  12      Recky    Six    94  female
31  32  Binn Rott  Seven    90  female
10  11     Ronald    Six    89  female

In [ ]:
df[(df["gender"]=="female") | (df["class"]=="Seven")].sort_values(by="mark")

    id         name  class  mark  gender
9   10     Big John   Four    55  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
0    1     John Deo   Four    75  female
23  24    Tiddy Now  Seven    78    male
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
27  28    Rojj Base  Seven    86  female
24  25     Giff Tow  Seven    88    male
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

In [ ]:
df[(df["gender"]=="female") | (df["class"]=="Seven")].sort_values(by=["id", "mark"])

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
## How many male and female students are there?
df["gender"].value_counts()

gender
male      17
female    16
Name: count, dtype: int64

In [ ]:
## Class and number of student
df["class"].value_counts()

class
Seven    10
Four      8
Six       7
Three     3
Nine      2
Five      2
Fifth     1
Eight     1
Name: count, dtype: int64